Solve third lesson
OUGHT/reactive_lumberjack pull request #3
Opened 2017-06-09 06:24 UTC by OUGHT

2017-06-09 11:52 UTC, blackleadsu requested changes

2017-06-09 11:52 UTC, blackleaden commented on src/components/BlogList.js
> +              likeAction={this.props.likeAction}
Хорошая практика - cформировать свой коллбэк для каждого blogItem: 
`likeAction={() => this.props.likeAction(item.id) }`. Это ощутимо лучше, чем опускать и аргументы, и экшн вниз по иерархии.

2017-06-09 11:52 UTC, blackleaden commented on src/components/BlogPage.js
> +    return (<BlogList items={this.state.items} likeAction={this.likeAction}/>)
На твоё усмотрение -- есть вариант биндить проще, сохраняя this в замыкании анонимной функции: `likeAction={(id) => this.lakeAction(id)}`

2017-06-10 07:56 UTC, OUGHT commented on src/components/BlogPage.js
> +    return (<BlogList items={this.state.items} likeAction={this.likeAction}/>)
Лично мне кажется, что это не является ни проще, ни красивее варианта с transform-class-properties =-)

2017-06-10 08:03 UTC, OUGHT commented on src/components/BlogList.js
> +              likeAction={this.props.likeAction}
Не совсем понял, зачем оборачивать это в двойной коллбэк - ведь результат функции likeAction уже и так является коллбэком. В остальном идею понял, переделаю.

2017-06-11 07:50 UTC, blackleadsu approved these changes

2017-06-16 12:58 UTC, merged